### ISSUE TITLE
v2 Bridge contracts deployment

### ISSUE THREAD

**Issue by pdyraga** [keep-network/tbtc-v2#438]
Team | Address
------------ | -------------
**Deployment Team** | `0x123694886DBf5Ac94DDA07135349534536D14cAf`
**Threshold Council** | `0x9f6e831c8f8939dc0c830c6e492e7cef4f9c2f5f`

# Prerequisites
- #431
- #433
- #434
- #436
- #437
- [ ] Transfer `VendingMachine@0x6590DFF6abEd7C077839E8227A4f12Ec90E6D85F` ownership from Keep Community multisig to Threshold Council (tx: `0x...`)

# Tag the new version
All steps done by the Deployment Team
- [ ] Tag `solidity/v1.0.0` in `keep-network/tbtc-v2`
- [ ] Sign `solidity/v1.0.0` commit hash

# Deploy and initialize the difficulty relay
All steps done by the Deployment Team
- [ ] Deploy `LightRelay` contract (address: `0x...`)
- [ ] Perform the `genesis` with a previous Bitcoin epoch using `genesisProofLength` of 20 blocks (tx: `0x...`)
- [ ] `retarget` the relay with the current Bitcoin epoch (tx: `0x...`)
- [ ] Set the authorization status to `true` (tx: `0x...`)

# Deploy v2 bridge contracts
All steps done by the Deployment Team
- [ ] Deploy `Bank` contract (address: `0x...`)
- [ ] Deploy `Bridge` implementation contract (address: `0x...`)
- [ ] Deploy `Bridge` proxy contract (address: `0x...`)
- [ ] Deploy `Bridge` `ProxyAdmin` contract (address: `0x...`)
- [ ] Initialize `Bridge` proxy contract (tx: `0x...`) with the following parameters: 
  - `_bank`: `Bank.address`
  - `_relay`: `LightRelay.address`
  - `_treasury`: `0x9f6e831c8f8939dc0c830c6e492e7cef4f9c2f5f` (Threshold Council or Treasury Guild?)
  - `_ecdsaWalletRegistry`: `0x46d52E41C2F300BC82217Ce22b920c34995204eb`
  - `_reimbursementPool`: `0x8adF3f35dBE4026112bCFc078872bcb967732Ea8`
  - `_txProofDifficultyFactor`: `6`
- [ ] Deploy `TBTCVault` contract (address: `0x...`) with the following parameters:
  - `_bank`: `Bank.address`
  - `_tbtcToken`: `0x18084fbA666a33d37592fA2633fD49a74DD93a88`
  - `_bridge`: `Bridge.address`
- [ ] Set `TBTCVault` as a trusted vault in the `Bridge` via `Bridge_proxy.setVaultStatus(TBTCVault.address, true)` (tx: `0x...`)
- [ ] Deploy `DonationVault` contract (address: `0x...`)
- [ ] Deploy `BridgeGovernance` contract (address: `0x...`) with the following parameters:
  - `_bridge`: `Bridge.address`
  - `_governanceDelay`: `24h`
- [ ] Deploy `MaintainerProxy` contract (address: `0x...`) with the following parameters:
  - `_bridge`: `Bridge.address`
  - `_reimbursementPool`: `0x8adF3f35dBE4026112bCFc078872bcb967732Ea8`
- [ ] Authorize `MaintainerProxy` contract as an SPV maintainer in `Bridge` contract (tx: `0x...`)
- [ ] Update `Bridge` reference in the `Bank` with `Bank.updateBridge` call (tx: `0x...`) 

# Adjust parameters for Chaosnet phase 1
All steps done by the Deployment Team

- [ ] Update deposit and redemption fee [DEPENDS on #431] (tx: `0x...`) 
- [ ] Update deposit dust threshold [DEPENDS ON #436] (tx: `0x...`) 
- [ ] Disable fraud challenges updating `Bridge`'s `fraudChallengeDepositAmount` to `type(uin96).max` [TO BE CONFIRMED BY #433] (tx: `0x...`) 
- [ ] Disable redemptions updating `Bridge`'s `redemptionDustThreshold` to `type(uint64).max` [TO BE CONFIRMED BY #437] (tx: `0x...`) 
- [ ] Disable moving funds updating `Bridge`'s `walletMaxAge` to `type(uint32).max` and `walletClosureMinBtcBalance` to `type(uint64).max` [TO BE CONFIRMED BY #434] (tx: `0x...`) 

Moving funds between wallets, fraud challenges, and redemption are disabled for Chaosnet phase 1. We update slashing amounts to reflect it. Slashing amounts will be set to appropriate values as we enable these features gradually.
- [ ] Set `Bridge`'s `movingFundsTimeoutSlashingAmount` to `0`
- [ ] Set `Bridge`'s `movedFundsSweepTimeoutSlashingAmount` to `0`
- [ ] Set `Bridge`'s `redemptionTimeoutSlashingAmount` to `0`
- [ ] Set `Bridge`'s `fraudSlashingAmount` to `0`

# Transfer contract ownership
All steps done by the Deployment Team
- [ ] Transfer `Bank` ownership to Threshold Council (tx: `0x...`)
- [ ] Transfer `Bridge` governance to `BridgeGovernance` contract (tx: `0x...`)
- [ ] Transfer `BridgeGovernance` ownership to Threshold Council (tx: `0x...`)
- [ ] Transfer `TBTCVault` ownership to Threshold Council (tx: `0x...`)
- [ ] Transfer `MaintainerProxy` ownership to Threshold Council (tx: `0x...`)
- [ ] Transfer `Bridge` `ProxyAdmin` contract ownership to Threshold Council (tx: `0x...`)

# Authorize contracts in ReimbursementPool
All steps done by the Threshold Council
- [ ] Authorize `Bridge` in `ReimbursementPool@0x8adF3f35dBE4026112bCFc078872bcb967732Ea8` (tx: `0x...`)
- [ ] Authorize `MaintainerProxy` in `ReimbursementPool@0x8adF3f35dBE4026112bCFc078872bcb967732Ea8` (tx: `0x...`)

# Initialize Wallet Owner
All steps done by the Threshold Council
- [ ] Initialize `Bridge` proxy as a wallet owner in `WalletRegistry_proxy@0x46d52E41C2F300BC82217Ce22b920c34995204eb` via `WalletRegistryGovernance@0x6aed6cC30D1b2770771052555d257Da86eD47fe8.initializeWalletOwner(Bridge_proxy.address)` (tx: `0x...`)

# Fund Reimbursement Pool
All steps done by the Threshold Council
- [ ] Send ETH to `ReimbursementPool@0x8adF3f35dBE4026112bCFc078872bcb967732Ea8`

 # Etherscan verification
All steps done by Deployment Team
- [ ] Verify `LightRelay` contract
- [ ] Verify `Bank` contract
- [ ] Verify `Bridge` contract
- [ ] Verify `TBTCVault` contract
- [ ] Verify `DonationVault` contract
- [ ] Verify `BridgeGovernance` contract
- [ ] Verify `MaintainerProxy` contract

# Package publication
Done by Deployment Team
- [ ] Publish v1.0.0 package of coverage pools to NPM

# Release notes
Done by Deployment Team
- [ ] Publish `solidity/v1.0.0` release notes in `keep-network/tbtc-v2`

# Upgrade v1<>v2 Vending Machine to TBTC Vault

⚠️ DANGER ZONE - PROCEED WITH CAUTION ⚠️ 

THERE IS NO WAY TO REVERT THIS ACTION

SIMULATE AND EXECUTE SEPARATELY

- [ ] Keep Tech Wallet: `VendingMachine@0x6590DFF6abEd7C077839E8227A4f12Ec90E6D85F.initiateVendingMachineUpgrade(TBTCVault.address)` 
- [ ] Threshold Council: `VendingMachine@0x6590DFF6abEd7C077839E8227A4f12Ec90E6D85F.finalizeVendingMachineUpgrade`

**Comment by lukasz-zimnoch** [comment]
Section "Deploy and initialize the difficulty relay" -> Shouldn't we authorize a proof submitter once we set the authorization status to `true`?
