### ISSUE TITLE
Cross-chain Tokenized Threshold BTC: Arbitrum module

### ISSUE THREAD

**Issue by pdyraga** [keep-network/tbtc-v2#545]
See https://github.com/keep-network/tbtc-v2/pull/542

Implement `cross-chain/arbitrum` module:
- [ ] Token contract inheriting from #543 
- [ ] Wormhole gateway contract inheriting from #544 
- [ ] Deployment scripts for Goerli
- [ ] Deployment scripts for Mainnet: L1 and L2
- [ ] CI build system for contracts
- [ ] CI build system for Goerli deploy
- [ ] Upgradeability for token and Wormhole gateway
- [ ] Mainnet deployment scenario issue https://github.com/keep-network/tbtc-v2/issues/577
