### ISSUE TITLE
EPIC: Finishing touches 💅

### ISSUE THREAD

**Issue by mhluongo** [keep-network/tbtc-v2#672]
* [ ] Comprehensive protocol documentation
* [ ] Faster redemptions
* [ ] Hardened sweeps
  * [ ] Today, tBTC is minted when an Minter requests it to be, and a veto period passes. If a Minter ignores your BTC deposit, it will still be included in a sweep proposed by a specialized maintainer, minted a few hours later when the SPV proof is submitted.
We’d like to be resilient to all specialized maintainers going down, ensuring users can still mint if they’re offline or have been tampered with.
* [ ] Retiring the beta staker program
  * [ ] Upgrading from threshold ECDSA / GG 18 to Schnorr / ROAST to mitigate staker DoS opportunities
  * [ ] Even larger wallets 🔥
* [ ] More sophisticated monitoring and testing

**Comment by erdogan** [comment]
Broke these down into separate EPICs as below: 

- [ ] https://github.com/threshold-network/pm/issues/31
- [ ] https://github.com/threshold-network/pm/issues/21
- [ ] https://github.com/threshold-network/pm/issues/32
- [ ] https://github.com/threshold-network/pm/issues/33
- [ ] https://github.com/threshold-network/pm/issues/30
