### ISSUE TITLE
Replace `bcoin` with `bitcoinjs-lib`

### ISSUE THREAD

**Issue by lukasz-zimnoch** [keep-network/tbtc-v2#695]
As decided in https://github.com/keep-network/tbtc-v2/issues/694, we aim to replace `bcoin` with `bitcoinjs-lib`. This task is capturing all the required work.

```[tasklist]
### Tasks
- [ ] https://github.com/keep-network/tbtc-v2/pull/693
- [ ] https://github.com/keep-network/tbtc-v2/pull/696
- [ ] https://github.com/keep-network/tbtc-v2/pull/700
- [ ] https://github.com/keep-network/tbtc-v2/pull/702
- [ ] https://github.com/keep-network/tbtc-v2/pull/703
- [ ] https://github.com/keep-network/tbtc-v2/pull/706
- [ ] https://github.com/keep-network/tbtc-v2/pull/707
- [ ] https://github.com/keep-network/tbtc-v2/pull/708
```
