### ISSUE TITLE
SDK final touches: Use `Hex` wherever applicable

### ISSUE THREAD

**Issue by lukasz-zimnoch** [keep-network/tbtc-v2#713]
Depends on: https://github.com/keep-network/tbtc-v2/issues/698

As pointed out in the [TODO](https://github.com/keep-network/tbtc-v2/blob/4f766f31d784d840c9f996bc6d4cb15bd756f214/typescript/src/index.ts#L16), we need to inspect the public components of the typescript library and replace all `string` representing hexadecimal data with `Hex`. This way we will make the API consistent and more friendly as the clients would not have to wonder about using the right string format. 
```[tasklist]
### Tasks
- [ ] https://github.com/keep-network/tbtc-v2/pull/709
- [ ] https://github.com/keep-network/tbtc-v2/pull/723
- [x] Check if all comments regarding hex conversions from https://github.com/keep-network/tbtc-v2/pull/705 are addressed
```
