### ISSUE TITLE
SDK final touches: Increase unit tests coverage

### ISSUE THREAD

**Issue by lukasz-zimnoch** [keep-network/tbtc-v2#714]
Depends on: https://github.com/keep-network/tbtc-v2/issues/698

This task is about re-visiting TODOs around unit tests and implementing missing unit tests to increase coverage. Specifically, this includes:

```[tasklist]
### Tasks
- [x] Cover the `Deposit.detectFunding` function
- [x] Cover the `Deposit.initiateMinting` function (parameter-less version)
- [x] Cover the `Deposit.getBitcoinAddress` function
- [x] Cover the `DepositsService.initiateDeposit` function
- [x] Add missing cases for `ElectrumClient.getTransaction` function
- [x] Check for other places that can be covered with unit tests. Focus on client-facing functions available through the `TBTC` entrypoint (ignore all components marked as `experimental` for now)
```
