### ISSUE TITLE
Explore and develop an alternative for the wallet coordinator mechanism

### ISSUE THREAD

**Issue by lukasz-zimnoch** [keep-network/tbtc-v2#737]
The current `WalletCoordinator` contract was an initial attempt to develop a wallet coordination mechanism without implementing a consensus mechanism in the off-chain client. This mechanism has been working well so far. However, it has a major drawback: it is a single point of failure as it relies on a small set of coordinator bots authorized to submit wallet action proposals. We need to replace it with something better. 

This task is about exploring possible alternatives and implementing the most promising ones.
```[tasklist]
### Tasks
- [ ] https://github.com/keep-network/tbtc-v2/pull/744
- [ ] https://github.com/keep-network/keep-core/pull/3744
- [ ] https://github.com/keep-network/keep-core/pull/3745
- [ ] https://github.com/keep-network/keep-core/pull/3747
- [ ] https://github.com/keep-network/keep-core/pull/3750
- [ ] https://github.com/keep-network/tbtc-v2/pull/756
- [ ] https://github.com/keep-network/keep-core/pull/3751
- [ ] https://github.com/keep-network/keep-core/pull/3752
- [x] Initial tests on testnet
```
