### ISSUE TITLE
Support for Base direct bridging

### ISSUE THREAD

**Issue by lukasz-zimnoch** [keep-network/tbtc-v2#750]
This task is about implementing support for Base direct bridging, based on the exploratory work done in https://github.com/keep-network/tbtc-v2/pull/704. 

The scope of this task includes:
- Implementation of the necessary L1 and L2 contracts
- Necessary contract deployments and upgrades
- Implementation of the support in the tBTC SDK
```[tasklist]
### Tasks
- [ ] https://github.com/keep-network/tbtc-v2/pull/778
- [ ] https://github.com/keep-network/tbtc-v2/pull/779
- [ ] https://github.com/keep-network/tbtc-v2/pull/792
- [ ] https://github.com/keep-network/tbtc-v2/pull/798
```
